FROM node:18-alpine

WORKDIR /app/frontend

# Copy package files
COPY dashboard/frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY dashboard/frontend/ ./

# Expose React default port
EXPOSE 3000

# Start React app
CMD ["npm", "run", "dev", "--", "--host"]

